// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/embedding/embedding.proto

package embedding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmbeddingRequest contains the prompt to embed
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_internal_embedding_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_embedding_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_internal_embedding_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// EmbeddingResponse contains the generated embedding vector
type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // repeated = array/slice in Go
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_internal_embedding_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_embedding_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_internal_embedding_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// EmbeddingBatchRequest contains multiple prompts
type EmbeddingBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompts       []string               `protobuf:"bytes,1,rep,name=prompts,proto3" json:"prompts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingBatchRequest) Reset() {
	*x = EmbeddingBatchRequest{}
	mi := &file_internal_embedding_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingBatchRequest) ProtoMessage() {}

func (x *EmbeddingBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_embedding_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingBatchRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_embedding_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *EmbeddingBatchRequest) GetPrompts() []string {
	if x != nil {
		return x.Prompts
	}
	return nil
}

// EmbeddingBatchResponse contains multiple embedding vectors
type EmbeddingBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbeddingResponse   `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingBatchResponse) Reset() {
	*x = EmbeddingBatchResponse{}
	mi := &file_internal_embedding_embedding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingBatchResponse) ProtoMessage() {}

func (x *EmbeddingBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_embedding_embedding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingBatchResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_embedding_embedding_proto_rawDescGZIP(), []int{3}
}

func (x *EmbeddingBatchResponse) GetEmbeddings() []*EmbeddingResponse {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

var File_internal_embedding_embedding_proto protoreflect.FileDescriptor

const file_internal_embedding_embedding_proto_rawDesc = "" +
	"\n" +
	"\"internal/embedding/embedding.proto\x12\tembedding\"*\n" +
	"\x10EmbeddingRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"1\n" +
	"\x11EmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\"1\n" +
	"\x15EmbeddingBatchRequest\x12\x18\n" +
	"\aprompts\x18\x01 \x03(\tR\aprompts\"V\n" +
	"\x16EmbeddingBatchResponse\x12<\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x1c.embedding.EmbeddingResponseR\n" +
	"embeddings2\xb7\x01\n" +
	"\x10EmbeddingService\x12I\n" +
	"\fGetEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponse\x12X\n" +
	"\x11GetEmbeddingBatch\x12 .embedding.EmbeddingBatchRequest\x1a!.embedding.EmbeddingBatchResponseB\x18Z\x16dli/internal/embeddingb\x06proto3"

var (
	file_internal_embedding_embedding_proto_rawDescOnce sync.Once
	file_internal_embedding_embedding_proto_rawDescData []byte
)

func file_internal_embedding_embedding_proto_rawDescGZIP() []byte {
	file_internal_embedding_embedding_proto_rawDescOnce.Do(func() {
		file_internal_embedding_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_embedding_embedding_proto_rawDesc), len(file_internal_embedding_embedding_proto_rawDesc)))
	})
	return file_internal_embedding_embedding_proto_rawDescData
}

var file_internal_embedding_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_embedding_embedding_proto_goTypes = []any{
	(*EmbeddingRequest)(nil),       // 0: embedding.EmbeddingRequest
	(*EmbeddingResponse)(nil),      // 1: embedding.EmbeddingResponse
	(*EmbeddingBatchRequest)(nil),  // 2: embedding.EmbeddingBatchRequest
	(*EmbeddingBatchResponse)(nil), // 3: embedding.EmbeddingBatchResponse
}
var file_internal_embedding_embedding_proto_depIdxs = []int32{
	1, // 0: embedding.EmbeddingBatchResponse.embeddings:type_name -> embedding.EmbeddingResponse
	0, // 1: embedding.EmbeddingService.GetEmbedding:input_type -> embedding.EmbeddingRequest
	2, // 2: embedding.EmbeddingService.GetEmbeddingBatch:input_type -> embedding.EmbeddingBatchRequest
	1, // 3: embedding.EmbeddingService.GetEmbedding:output_type -> embedding.EmbeddingResponse
	3, // 4: embedding.EmbeddingService.GetEmbeddingBatch:output_type -> embedding.EmbeddingBatchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_embedding_embedding_proto_init() }
func file_internal_embedding_embedding_proto_init() {
	if File_internal_embedding_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_embedding_embedding_proto_rawDesc), len(file_internal_embedding_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_embedding_embedding_proto_goTypes,
		DependencyIndexes: file_internal_embedding_embedding_proto_depIdxs,
		MessageInfos:      file_internal_embedding_embedding_proto_msgTypes,
	}.Build()
	File_internal_embedding_embedding_proto = out.File
	file_internal_embedding_embedding_proto_goTypes = nil
	file_internal_embedding_embedding_proto_depIdxs = nil
}
